workflows:
  ios-native-workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true

    environment:
      ios_signing:
        certificates:
          - daotqcert
        provisioning_profiles:
          - daotqmobileprovision
      vars:
        XCODE_PROJECT_NAME: "vertd"
        XCODE_PROJECT: "vertd.xcodeproj"
        XCODE_SCHEME: "vertd"
        BUNDLE_ID: "vn.gbsofit.charger"

    scripts:
      - name: Install XcodeGen
        script: |
          if ! command -v xcodegen >/dev/null 2>&1; then
            brew update
            brew install xcodegen
          fi

      - name: Generate Xcode project
        script: |
          rm -rf "$CM_BUILD_DIR/$XCODE_PROJECT"
          rm -rf "$CM_BUILD_DIR/$XCODE_PROJECT_NAME.xcodeproj"

          cd "$CM_BUILD_DIR"
          xcodegen generate \
            --spec "project.yml" \
            --project "$XCODE_PROJECT_NAME"

          PROJECT_PATH=$(find "$CM_BUILD_DIR" -maxdepth 3 -type d -name "$XCODE_PROJECT" | head -n 1)
          if [ -z "$PROJECT_PATH" ]; then
            echo "Generated project '$XCODE_PROJECT' was not found."
            echo "Available xcodeproj directories:"
            find "$CM_BUILD_DIR" -maxdepth 4 -type d -name "*.xcodeproj"
            exit 1
          fi

          echo "Resolved Xcode project path: $PROJECT_PATH"
          echo "XCODE_PROJECT_PATH=$PROJECT_PATH" >> "$CM_ENV"

      - name: Resolve signing values from provisioning profile
        script: |
          PROFILE_PATH=$(find "$HOME/Library/MobileDevice/Provisioning Profiles" -name "*.mobileprovision" | head -n 1)
          if [ -z "$PROFILE_PATH" ]; then
            echo "No provisioning profile found under $HOME/Library/MobileDevice/Provisioning Profiles"
            exit 1
          fi

          security cms -D -i "$PROFILE_PATH" > profile.plist
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print :Name" profile.plist)
          TEAM_ID=$(/usr/libexec/PlistBuddy -c "Print :TeamIdentifier:0" profile.plist)

          echo "Resolved provisioning profile: $PROFILE_NAME"
          echo "Resolved team id: $TEAM_ID"

          echo "PROFILE_NAME=$PROFILE_NAME" >> "$CM_ENV"
          echo "TEAM_ID=$TEAM_ID" >> "$CM_ENV"

      - name: Build IPA for distribution
        script: |
          set -euo pipefail
          BUILD_ROOT="$(cd "${CM_BUILD_DIR:-.}" && pwd)"
          PROJECT_PATH="${XCODE_PROJECT_PATH:-}"
          TEAM="${TEAM_ID:-}"
          PROFILE="${PROFILE_NAME:-}"
          BUNDLE="${BUNDLE_ID:-}"
          SCHEME="${XCODE_SCHEME:-}"

          if [ -z "$PROJECT_PATH" ]; then
            CANDIDATE_PROJECT="$(find "$BUILD_ROOT" -maxdepth 4 -type d -name "*.xcodeproj" | head -n 1)"
            if [ -n "$CANDIDATE_PROJECT" ]; then
              PROJECT_PATH="$CANDIDATE_PROJECT"
              echo "Resolved XCODE_PROJECT_PATH from filesystem: $PROJECT_PATH"
            fi
          fi

          if [ -z "$PROJECT_PATH" ] || [ ! -d "$PROJECT_PATH" ]; then
            echo "Invalid XCODE_PROJECT_PATH: '$PROJECT_PATH'"
            find "$BUILD_ROOT" -maxdepth 4 -type d -name "*.xcodeproj"
            exit 1
          fi
          if [ -z "$TEAM" ] || [ -z "$PROFILE" ] || [ -z "$BUNDLE" ] || [ -z "$SCHEME" ]; then
            echo "Missing signing variables:"
            echo "TEAM_ID='$TEAM'"
            echo "PROFILE_NAME='$PROFILE'"
            echo "BUNDLE_ID='$BUNDLE'"
            echo "XCODE_SCHEME='$SCHEME'"
            exit 1
          fi

          EXPORT_OPTIONS_PLIST="$BUILD_ROOT/export_options.plist"
          cat > "$EXPORT_OPTIONS_PLIST" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>$TEAM</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE</key>
              <string>$PROFILE</string>
            </dict>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          if [ ! -f "$EXPORT_OPTIONS_PLIST" ]; then
            echo "Failed to create export options plist at $EXPORT_OPTIONS_PLIST"
            exit 1
          fi
          if [ "$EXPORT_OPTIONS_PLIST" = "." ] || [ "$EXPORT_OPTIONS_PLIST" = "./" ]; then
            echo "Invalid export options plist path: '$EXPORT_OPTIONS_PLIST'"
            exit 1
          fi

          echo "Using project: $PROJECT_PATH"
          echo "Using export options plist: $EXPORT_OPTIONS_PLIST"
          ls -la "$EXPORT_OPTIONS_PLIST"

          xcode-project build-ipa \
            --project "$PROJECT_PATH" \
            --scheme "$SCHEME" \
            --export-options-plist "$EXPORT_OPTIONS_PLIST" \
            --archive-xcargs "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=$TEAM PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE PROVISIONING_PROFILE_SPECIFIER=$PROFILE"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
