workflows:
  ios-native-workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true

    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.sitien173.vertd
      vars:
        XCODE_PROJECT: "vertd.xcodeproj"
        XCODE_SCHEME: "vertd"
        BUNDLE_ID: "com.sitien173.vertd"

    scripts:
      - name: Validate Xcode project file
        script: |
          if grep -q "Placeholder project file scaffold" "$CM_BUILD_DIR/$XCODE_PROJECT/project.pbxproj"; then
            echo "The project.pbxproj file is still placeholder content."
            echo "Open the project in Xcode on macOS and commit the real project file before running Codemagic builds."
            exit 1
          fi

      - name: Configure code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
