name: vertd

options:
  deploymentTarget:
    iOS: "16.3"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  vertd:
    type: application
    platform: iOS
    sources:
      - path: vertd
    info:
      path: vertd/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: vn.gbsofit.charger
        CODE_SIGN_STYLE: Manual

  vertdTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: vertdTests
    dependencies:
      - target: vertd
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: vn.gbsofit.chargerTests
